pipeline {
    agent {
        docker {
            image 'node'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        DISCORD_WEBHOOK_URL = 'https://discord.com/api/webhooks/1291652946894782565/Z2DLNdFmdQfLJ2dUX5kBAgIGEdax7Gz-VWICJvHCcMHVXqC0hIlbwvWGMy8ICpfuUeNj' // Your webhook URL
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
    post {
        success {
            script {
                sendDiscordNotification("Build succeeded: ${env.BUILD_URL}")
            }
        }
        failure {
            script {
                sendDiscordNotification("Build failed: ${env.BUILD_URL}")
            }
        }
    }
}

def sendDiscordNotification(String message) {
    def payload = [
        content: message
    ]

    httpRequest(
        url: DISCORD_WEBHOOK_URL,
        httpMode: 'POST',
        contentType: 'APPLICATION_JSON',
        requestBody: groovy.json.JsonOutput.toJson(payload)
    )
}
